# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       木土金王可
description: ''
author:      木土金王可
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://dujinke.com/' # The base hostname & protocol for your site
email:       'okjaketo@gmail.com'
twitter:     'https://www.twitter.com/okjaketo'
instagram:   'https://www.instagram.com/okjaketo/'
youtube:     'https://www.youtube.com/channel/UCY4dkiRPDkuT2Z05Pha2GVw'

markdown:  kramdown
permalink: pretty
paginate:  8

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages
  - .well-known

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
